### ISSUE TITLE
Add River: Chicago Water Temperatures

### ISSUE THREAD

**Issue by rhyolight** [rhyolight/river-view#2]
[https://data.cityofchicago.org/Parks-Recreation/Beach-Water-Quality-Automated-Sensors-2015-Water-T/3ipq-j3gd](https://data.cityofchicago.org/Parks-Recreation/Beach-Water-Quality-Automated-Sensors-2015-Water-T/3ipq-j3gd)

JSON: https://data.cityofchicago.org/api/views/3ipq-j3gd/rows.json

**Comment by rhyolight** [comment]
I'm doing this one.

**Comment by cogmission** [comment]
I won't be able to join in producing these for a bit anyway, it's ok. I'm having an organization crisis I need to shore up :-)

**Comment by rhyolight** [comment]
Good luck!

**Comment by cogmission** [comment]
:-P

**Comment by rhyolight** [comment]
:boom: https://river-view.herokuapp.com/chicago-water-temps/Montrose%20Beach/data.html
